name: hospital_attendance_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management / utilities - Working versions
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  bloc: ^8.1.4

  # Freezed (runtime annotation) - Working versions
  freezed_annotation: ^2.4.4

  # JSON support commonly used with freezed - Working
  json_annotation: ^4.9.0

  # Injectable - runtime - Working version
  injectable: ^2.4.4
  
  # UI Framework - Latest
  forui: ^0.15.1
  forui_assets: ^0.15.0
  
  # Development tools - Working versions
  device_preview: ^1.2.0
  go_router: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code generators / build - Working versions
  build_runner: ^2.4.9
  freezed: ^2.5.2
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0
  go_router_builder: ^3.0.0

flutter:
  uses-material-design: true
