import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FToastStyle toastStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FToastStyle(
  decoration: BoxDecoration(
    border: Border.all(color: colors.border),
    borderRadius: style.borderRadius,
    color: colors.background,
  ),
  iconStyle: IconThemeData(color: colors.primary, size: 18),
  titleTextStyle: typography.sm.copyWith(
    color: colors.primary,
    fontWeight: FontWeight.w500,
  ),
  titleSpacing: 5,
  descriptionTextStyle: typography.sm.copyWith(
    color: colors.mutedForeground,
    overflow: TextOverflow.ellipsis,
  ),
  enterExitDuration: const Duration(milliseconds: 400),
  enterCurve: Curves.easeOutCubic,
  exitCurve: Curves.easeOutCubic,
  entranceExitOpacity: 0.0,
  transitionDuration: const Duration(milliseconds: 400),
  transitionCurve: Curves.easeOutCubic,
  swipeCompletionDuration: const Duration(milliseconds: 150),
  swipeCompletionCurve: Curves.easeInCubic,
  constraints: const BoxConstraints(maxHeight: 250, maxWidth: 400),
  padding: const EdgeInsets.all(16),
  iconSpacing: 10,
  suffixSpacing: 12,
);
